name: Frontend CI

on:
  pull_request:
    branches: [main, cicd]
  push:
    branches: [cicd]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Verify build contains index.html
        run: ls -l dist

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Serve build folder
        run: npx serve -s dist -l 45607 &
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:45607

      - name: Verify Index Exists
        run: curl -I http://localhost:45607/index.html

      - name: Run Lighthouse CI
        run: lhci autorun --config=./lighthouserc.json
